sudo: required
os: linux
language: minimal

services:
  - docker

script:
  - echo "Daily push to Docker Hub"
  - docker build --no-cache -t llgameserverbot/push-daily .
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
  - docker push llgameserverbot/push-daily;
